### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email" : "test@test.com",
    "password":"password123",
    "username":"testuser"
}


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password":"password123"
}

### Protected route without Token
GET http://localhost:5000/api/debates/protected


### Protected route with Token
GET http://localhost:5000/api/debates/protected
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXBxdzBzcHkwMDAweXhoaXVkZXN2dTV2IiwiaWF0IjoxNzgwMDU3Mjg2LCJleHAiOjE3ODA2NjIwODZ9.1PvtVQU1b6CNBao-L4Dj7vnpssX9XJrBQ7EjUWp4COI

### Start Debate
POST http://localhost:5000/api/debates/start
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXBxdzBzcHkwMDAweXhoaXVkZXN2dTV2IiwiaWF0IjoxNzgwNjM5MTE4LCJleHAiOjE3ODEyNDM5MTh9.f0T0uN4fNUSI_pawDyL3sBSD-L9kjJUwJFriYuCOKqE

{
  "topic": "Social media does more harm than good",
  "userSide": "for"
}


### Send Argument
POST http://localhost:5000/api/debates/argue
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXBxdzBzcHkwMDAweXhoaXVkZXN2dTV2IiwiaWF0IjoxNzgwNjM5MTE4LCJleHAiOjE3ODEyNDM5MTh9.f0T0uN4fNUSI_pawDyL3sBSD-L9kjJUwJFriYuCOKqE

{
  "sessionId":"cmq0im8600001flexy6pn5kwt",
  "argument": "Social media has proven to increase anxiety and depression especially in teenagers"
}


### Analyse Debate
POST http://localhost:5000/api/debates/analyse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbXBxdzBzcHkwMDAweXhoaXVkZXN2dTV2IiwiaWF0IjoxNzgwNjM5MTE4LCJleHAiOjE3ODEyNDM5MTh9.f0T0uN4fNUSI_pawDyL3sBSD-L9kjJUwJFriYuCOKqE

{
    "sessionId":"cmq0im8600001flexy6pn5kwt"
}